---
title: "Relatório 3 - Estatística"
subtitle: "Fazendo algumas análises em R"
date: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sumário"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 2  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table headerK
    theme: cosmo  # many options for theme, this one is my favorite.
    highlight: zenburn  # specifies the syntax highlighting style
    #css: my.css   # you can add your custom css, should be in same folder
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup opts_chunk, include=FALSE}
# chunk options:
knitr::opts_chunk$set(echo = T, include = T, eval=T,
                      warning = F, error = T,
                      message = F, out.width = "75%",
                      fig.align = 'center',
                      results = "markup")
```

------------------------------------------------------------------------

# Dados

A seguir é feita a leitura do conjunto de dados a ser utilizado na atividade. Os dados são referentes ao contexto de aplicação de fertilantes em produções e a possível presença de pragas. 

```{r}
#df <- read.csv("~/Downloads/dados_atividade1.xlsx - Planilha1.csv")
#head(df)
```

```{r}
df <- read.csv("~/GitHub/MAF261-Experimental_Statistics/relatorio3/dados_atividade1.xlsx - Planilha1.csv")
head(df)
```

A partir da visualização do conjunto de dados a ser utilizado, é possível observar que o dataset é composto por 4 colunas: uma para o id (ID) da instância do dado,  uma referente ao valor da produção (Producao), uma para indicar se houve a presença ou não de pragas (Praga) naquela produção  e uma para informar qual o tipo de fertilizante empregado.

Tem-se por intuito, inicialmente, realizar análises com base nos fertilizantes para os valores de produção, logo que há diferentes tratamentos sendo aplicados. 

```{r, results="asis"}
#install.packages("daewr")
library("daewr")
library("kableExtra")
kable(df, align='c')
```

# Descritivas

De maneira a se desenvolver um entendimento inicial dos dados dispostos, foi realizada algumas análises descritivas dos dados, apresentadas a seguir.

- Referente a variável de produção:

```{r}
library(tidyverse)
df |> group_by(Fertilizante) |> 
  summarise(media=mean(Producao), desv.pad=sd(Praga))|>
  kable(align='c', digits=2)
```

* A partir das informações das médias das produções para cada tipo de tratamento expostas acima, tem-se uma suspeita de que, aparentemente, existe alguma diferença entre os tratamentos.

* Ao se observar o gráfico abaixo, tal suspeita torna-se mais concreta, visto que as médias entre os experimentos estão bem diferentes. É possível observar que o tratamento B apresenta valores de produção superiores aos restantes, enquanto o tratamento C consiste dos valores mais baixos.

* Uma maneira de identificar se existe alguma diferença significativa entre as médias é por meio da realização de um teste ANOVA.

```{r}
df |> ggplot(aes(x=Fertilizante, y=Producao, color=Fertilizante)) + 
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.2)
```

# ANOVA para dados binários
## Regressão Logística
```{r}
modelo <- glm(Praga ~ Fertilizante, data = df, family = binomial(link = "logit"))
summary(modelo)
```

## ANOVA
```{r}
anova(modelo, test = "Chisq")
```


# ANOVA

Como queremos verificar se existe alguma diferença entre os tratamentos, utilizando a notação de testes de hipótese, o que desejamos testar pode ser representado da seguinte maneira: 
$$H_0: \mu_{A} = \mu_{B} = \mu_{C} = \mu_{D}$$
Ou seja, a hipótese nula dos dados é que todas as médias de produção para os diferentes fertilizantes são iguais. Aplicando a anova: 

```{r}
m <- aov(Producao ~ Fertilizante, data = df)
summary(m) 
```

A partir das informações fornecidas com a aplicação da ANOVA, foi encontrado como p-valor o resultado 7.66e-06. Trata-se de um valor bem menor ao nível de significância estabelecido para o teste, indicado que há evidência para rejeitar a hipótese nula. Considerando isso, a suspeita anterior de que haveria uma diferença entre as médias das produções para os diferentes tratamentos é confirmada pelo teste.

# Pressupostos

Em relação ao teste aplicado previamente, é importante comentar sobre as suposições realizadas para sua aplicação seja válida:
  - Populações normalmente distribuídas;
  - Populações tem mesma variância;
  - Amostras são aleatórias e mutuamente independentes;
  
Já abordando sobre os resíduos, podemos observar como eles se comportam.

O modelo que estamos considerando diz que uma observação de uma produção para um dado tratamento é igual a média para aquele tratamento somado ao seu respectivo resíduo, como é mostrado a seguir: $$y_{ij} = \mu_i + \epsilon_{ij}$$
Partindo disto, pode-se definir o resíduo como o valor da observação menor a média amostral do tratamento. A expressão é apresentada a seguir:
$$e_{ij} = y_{ij} - \bar{y}_{i\cdot}$$

```{r}
residuo <- m$residuals
dado <- data.frame(id=1:12, residuo=residuo)
kable(dado)
```

Na exposição acima é possível realizar uma observação inicial quanto aos resíduos encontrados pela ANOVA.

## Resíduo versus tratamento

```{r}
plot(m, which=5, pch=19) 
```

O gráfico acima apresenta a relação entre os tratamentos e os valores dos resíduos. A partir dele, esperava-se observar que os valores para todos os tratamentos estivessem próximos de zero caso a hipótese nula fosse verdadeira.

## Resíduo versus valor ajustado

Como o modelo é
$$y_{ij}=\mu_i+\epsilon_{ij},\;\;\;\;\; \epsilon_{ij}\sim N(0, \sigma^2)$$
então o valor ajustado é $$\hat{y}_{ij}=\bar{y}_{i\cdot}$$

```{r, results='asis'}
library(tidyverse)
df |> group_by(Fertilizante) |> 
  summarise(media = mean(Producao), desv.pad = sd(Producao)) |>
  kable(align='c', digits=2)
```

```{r}
plot(m, which=1, pch=19)
```

## Normalidade dos resíduos

A normalidade dos resíduos é um pressuposto importante para o estudo das médias dos tratamentos utilizando a ANOVA. Para realizar uma análise referente a eles, pode-se utilizar um gráfico ggplot. Nele, para se observar a normalidade dos resíduos, os valores devem seguir uma relação linear e estarem próximos da reta presente no gráfico.

```{r}
plot(m, which=2, pch = 19)
```

Para auxiliar na análise, é possível utilizar o recurso de um envelope a ser desenhado no gráfico que irá indicar uma "faixa de normalidade". Os pontos que fugirem da faixa podem apontar para uma falha na normalidade.

```{r}
library("car") # se necessário: install.packages("car")
qqPlot(m$residuals, pch=19, col.lines="darkred", id=F)
```

## Testando a normalidade dos resíduos

Para testar a normalidade é possível aplicar o teste de Shapiro-Wilks. As hipóteses do teste são: 

$$H_{0} = \text{Testes seguem uma distribuição normal}\\
  H_{1} = \text{Testes não seguem uma distribuição normal}$$

Aplicando o teste: 

```{r}
shapiro.test(m$residuals)
```

Com um nível de relevância p = 0.05, é possível observar que não temos evidências suficientes para rejeitar a hipótese nula, dessa forma podemos assumir que os dados são normais. O pressuposto para a normalidade dos resíduos é válido. 

# Testes para homogeneidade na variância

### F

É possível utilizar um teste F para comparar duas variâncias. As hipóteses para o teste F são: 

$$ H_{0} = \text{As variâncias são iguais}\\ H_{1} = \text{As variâncias são diferentes}$$

#### Par a par {.unnumbered}

**A e B**

```{r}
var.test(Producao ~ Fertilizante, data=df[df$Fertilizante=="A" | df$Fertilizante=="B",])
```

**A e C**

```{r}
var.test(Producao ~ Fertilizante, data=df[df$Fertilizante=="A" | df$Fertilizante=="C",])
```

**A e D**

```{r}
var.test(Producao ~ Fertilizante, data=df[df$Fertilizante=="A" | df$Fertilizante=="D",])
```

**B e C**

```{r}
var.test(Producao ~ Fertilizante, data=df[df$Fertilizante=="C" | df$Fertilizante=="B",])
```

**B e D**

```{r}
var.test(Producao ~ Fertilizante, data=df[df$Fertilizante=="D" | df$Fertilizante=="B",])
```

**C e D**

```{r}
var.test(Producao ~ Fertilizante, data=df[df$Fertilizante=="C" | df$Fertilizante=="D",])
```

Observando todos os testes par a par acima, é possível observar que aparentemente existe homogeniedade entre as variâncias. isso satisfaz um pressuposto importante da anova. 

### Bartlett {.unnumbered}

```{r}
bartlett.test(Producao ~ Fertilizante, data=df)
```

O teste de barlett ainda confirma isso. 

<!-- ------------------------------------------------------------- -->

------------------------------------------------------------------------